name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Test
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
        run: npm run wdio:bs-android
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
